### PR TITLE
Do averaging in MATLAB when X6 is in DIGITIZER mode.

### PR DESCRIPTION
**Pull request by blakejohnson**

### CODE REVIEW

**Comment by caryan** [comment]
I had a version in feature/x6-digitizer-mode but I think yours looks more complete.  I also have a branch in PyQLab for the GUI stuff.  I wanted to test all of them in the experiment before merging.

**Comment by blakejohnson** [comment]
Yeah, I unfortunately duplicated your work on the python side, too, and didn't realize it until I went to push the change up to GitHub.

**Comment by blakejohnson** [comment]
On the python side we were nearly identical, except that I made AVERAGER and DIGITIZER all caps in the enum. I didn't know what would happen in `set.digitizerMode()` if you passed a lowercase string, and was too lazy to find out or to inject case-conversion code.

**Comment by caryan** [comment]
@dieris says it works so we're good to go

**Comment by dieris** [comment]
unfortunately the branch I tested was x6-digitizer-mode, and not stream-selector-mode. Sorry for the oversight, testing it now (not successfully yet)

**Pull request merged**
