### PR TITLE
Force lock segments for single-shot mode

### PR DESCRIPTION
**Pull request by dieris**
This is a step back, but in single-shot mode, the segment number is typically a multiple of the
number of sequences. Either we have a multiplier field to specify the number of shots, or we manually set the total number of segments. In either case, a shortcut for the digitizer settings is helpful.

### CODE REVIEW

**Comment by blakejohnson** [comment]
Diego, can you change the merge target to `develop`?

**Comment by blakejohnson** [comment]
How about we interpret a numeric input argument as the number of shots? See the last commit.

**Comment by dieris** [comment]
good idea

**Comment by dieris** [comment]
is there a way to change the merge target, other than closing and opening a new PR?

**Comment by blakejohnson** [comment]
I think if you click the edit button in the upper right corner you can change it?

**Comment by dieris** [comment]
that only edits the title :(

**Comment by blakejohnson** [comment]
Bummer, I guess I'll just close this and merge it by hand.

**Pull request closed without merging**
