### PR TITLE
Feature fixed windows

### PR DESCRIPTION
**Pull request by CoherenceController**
Sets standard plots to fixed windows, instead of opening a new window per plot. The assignment of figure numbers is arbitrary, though, and may overwrite other plots. 

Also adds some label identifier to mixer calibration plots.

### CODE REVIEW

**Comment by blakejohnson** [comment]
@dieris I completely understand what drives the desire for this, but I'm not completely sold on the implementation. What would be great would be to have a way to give a plot a name/label and register that in the global namespace, then to be able to access that from several contexts.

What do you think, @caryan?

**Comment by dieris** [comment]
yes, I agree it's a hack. I used the pull request feature to present the problem. If we can use something like the matlab preferences, then we could save the window numbers/names there. If no preference exists, then it would create a new window instead. Other ideas?

**Comment by caryan** [comment]
I really don't like magic figure numbers.  I see a couple solutions.

1. Why can't we use the same trick we use for the experiment streaming plots with a persistent figure handle with hidden visibility. 
2. More along @blakejohnson 's line I've used ``findobj`` in the past to have fixed figure windows with a given label (e.g. title).

**Comment by dieris** [comment]
sure, I like the existing solution 1, I'll do something like that.

**Comment by blakejohnson** [comment]
This looks good enough to merge.

**Pull request merged**
