### PR TITLE
optimizer_mixer: Added lookup of logical channel frequency for SSBFreq

### PR DESCRIPTION
**Pull request by bcdonovan**
Added a function to lookup the frequency to be used for mixer calibration based on the contents of the LogicalChannel. This will prevent the manual editing of the optimize_mixer.json file when switching logical channels.

Needs to be tested on a experiment machine before merge. PR open for comments.

### CODE REVIEW

**Comment by blakejohnson** [comment]
I think maybe @caryan and I disagree on the appropriate procedure. The mixer amplitude imbalance and phase skew *should* be independent of the offset frequency. So, any observed `SSBFreq` dependence isn't due to a mixer imperfection but an AWG imperfection. My preference would be to always calibrate the mixer with some small frequency, say ~20 MHz, and then actually solve our channel skew issue in the APS2.

Am I the minority vote here?

**Comment by caryan** [comment]
I agree in principle, but in practice until we nail that issue down we might as well get the best image suppression we can for the frequency we're operating at.

**Comment by blakejohnson** [comment]
In that case, can we at least have this choice be a configurable parameter?

**Comment by dieris** [comment]
I think I agree with @caryan. Best to have suppression using the actual SSBFreq in use, although this may lose meaning when we do multiplexing.

**Comment by blakejohnson** [comment]
@dieris Right, as soon as we have multiplexed control the issue becomes much more complicated unless we can assume that the mixer response is roughly flat over the IF bandwidth.

**Comment by bcdonovan** [comment]
@blakejohnson I have exposed an overrideSSBFreq parameter in optimize_mixer to control the override. Passing a non-zero value will allow the override to lookup from the LogicalChannel.

**Pull request closed without merging**
